deploy:
    needs: test
    runs-on: ubuntu-latest
    if: always() # This job-level 'if' is fine as it doesn't use secrets
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Send Allure Report Email
        # Map secrets to environment variables for this step
        env:
          SMTP_USER_EXISTS: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASS_EXISTS: ${{ secrets.SMTP_PASSWORD }}
        # Now use the env context in your if condition
        if: ${{ (needs.test.result == 'success' || needs.test.result == 'failure') && env.SMTP_USER_EXISTS != '' && env.SMTP_PASS_EXISTS != '' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }} # Still use secrets directly here for the action's input
          password: ${{ secrets.SMTP_PASSWORD }} # Still use secrets directly here for the action's input
          subject: >
            Allure Report - ${{ github.repository }} | Status: ${{ needs.test.result }} | Event: ${{ github.event_name }}
          to: saivamsikolla@gmail.com
          from: GitHub Actions CI <${{ secrets.SMTP_USERNAME }}>
          body: |
            Hello,

            The automation test run for '${{ github.repository }}' has completed.
            Run Status: **${{ needs.test.result }}**

            Repository      : ${{ github.repository }}
            Workflow        : ${{ github.workflow }}
            Run ID          : ${{ github.run_id }}
            Run Number      : ${{ github.run_number }}
            Event Type      : ${{ github.event_name }}
            Triggered By    : ${{ github.actor }}
            Branch          : ${{ github.ref_name }}
            Commit          : https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            Commit Message  : ${{ needs.test.outputs.commit_message_text }}

            Test Summary:
            Total Tests     : ${{ needs.test.outputs.total }}
            Tests Passed    : ${{ needs.test.outputs.passed }}
            Tests Failed    : ${{ needs.test.outputs.failed }}
            Duration        : ${{ needs.test.outputs.duration }} seconds

            View the full Allure Report:
            ${{ steps.deployment.outputs.page_url }}

            Regards,
            GitHub Actions CI