name: CI with Dynamic Allure Report and Email

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    outputs:
      total: ${{ steps.summary.outputs.total }}
      passed: ${{ steps.summary.outputs.passed }}
      failed: ${{ steps.summary.outputs.failed }}
      duration: ${{ steps.summary.outputs.duration }}
      commit_message_text: ${{ steps.commit_info.outputs.commit_message_text }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies (jq and bc for summary)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq bc

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements.txt

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | cut -d' ' -f3)
          CHROME_DRIVER_VERSION_FULL=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$(echo $CHROME_VERSION | cut -d'.' -f1,2,3))
          wget -qO chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION_FULL}/chromedriver_linux64.zip
          sudo unzip -o chromedriver_linux64.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          rm chromedriver_linux64.zip

      - name: Install Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Install GeckoDriver
        run: |
          GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r .tag_name)
          wget -qO geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
          sudo tar -xzf geckodriver.tar.gz -C /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver
          rm geckodriver.tar.gz

      - name: Install Microsoft Edge
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common apt-transport-https ca-certificates curl
          wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable

      - name: Install MSEdgeDriver
        run: |
          EDGEDRIVER_VERSION=$(curl -s https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/LATEST_STABLE | iconv -f utf-16le -t utf-8 | sed 's/^[ \t]*//;s/[ \t]*$//')
          wget -qO msedgedriver.zip "https://msedgedriver.azureedge.net/${EDGEDRIVER_VERSION}/edgedriver_linux64.zip"
          sudo unzip -o msedgedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/msedgedriver
          rm msedgedriver.zip

      - name: Make run_tests.sh executable
        run: chmod +x ./run_tests.sh

      - name: Run Tests (All browsers, parallel, no HTML report from script)
        run: ./run_tests.sh --all-browsers --parallel-browsers -p 2 --no-report

      - name: Generate Allure Report HTML
        id: allure_report_generation
        run: |
          ALLURE_VERSION="2.27.0"
          if [ -d "allure-results/parallel-multi-browser" ] && [ "$(ls -A allure-results/parallel-multi-browser)" ]; then
            wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.zip
            unzip allure-${ALLURE_VERSION}.zip
            ./allure-${ALLURE_VERSION}/bin/allure generate allure-results/parallel-multi-browser --clean -o allure-report
            rm allure-${ALLURE_VERSION}.zip
            rm -rf allure-${ALLURE_VERSION}
          else
            echo "Error: allure-results/parallel-multi-browser is missing or empty. Ensure tests generate valid results."
            exit 1
          fi

      - name: Upload Allure Report Artifact for GitHub Pages
        if: success() || failure()
        run: |
          if [ -d "./allure-report" ]; then
            echo "Uploading Allure report artifact..."
            tar -czf allure-report.tgz -C ./ allure-report
          else
            echo "Warning: allure-report directory not found. Skipping upload."
            mkdir empty-report && tar -czf allure-report.tgz -C ./ empty-report
          fi
        # Upload artifact step
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report

      - name: Extract Test Summary
        if: success() || failure()
        id: summary
        run: |
          STATS_FILE="allure-report/widgets/summary.json"
          if [ -f "$STATS_FILE" ]; then
            TOTAL=$(jq '.statistic.total // 0' $STATS_FILE)
            PASSED=$(jq '.statistic.passed // 0' $STATS_FILE)
            FAILED=$(jq '.statistic.failed // 0' $STATS_FILE)
            DURATION_MS=$(jq '.time.duration // 0' $STATS_FILE)
            if ! [[ "$DURATION_MS" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
              DURATION_MS=0
            fi
            DURATION_SEC=$(echo "scale=2; $DURATION_MS / 1000" | bc)
            echo "total=$TOTAL" >> $GITHUB_OUTPUT
            echo "passed=$PASSED" >> $GITHUB_OUTPUT
            echo "failed=$FAILED" >> $GITHUB_OUTPUT
            echo "duration=$DURATION_SEC" >> $GITHUB_OUTPUT
            echo "Summary extracted: Total=$TOTAL, Passed=$PASSED, Failed=$FAILED, Duration=${DURATION_SEC}s"
          else
            echo "Warning: summary.json not found at $STATS_FILE. Setting default values."
            echo "total=0" >> $GITHUB_OUTPUT
            echo "passed=0" >> $GITHUB_OUTPUT
            echo "failed=0" >> $GITHUB_OUTPUT
            echo "duration=0.00" >> $GITHUB_OUTPUT
          fi

      - name: Get Commit Message for Email
        id: commit_info
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          COMMIT_MSG="${COMMIT_MSG//'%'/'%25'}"
          COMMIT_MSG="${COMMIT_MSG//$'\n'/'%0A'}"
          COMMIT_MSG="${COMMIT_MSG//$'\r'/'%0D'}"
          echo "commit_message_text=$COMMIT_MSG" >> $GITHUB_OUTPUT

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Send Allure Report Email
        env:
          SMTP_USER_EXISTS: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASS_EXISTS: ${{ secrets.SMTP_PASSWORD }}
        if: ${{ (needs.test.result == 'success' || needs.test.result == 'failure') && env.SMTP_USER_EXISTS != '' && env.SMTP_PASS_EXISTS != '' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: >
            Allure Report - ${{ github.repository }} | Status: ${{ needs.test.result }} | Event: ${{ github.event_name }}
          to: saivamsikolla@gmail.com
          from: GitHub Actions CI <${{ secrets.SMTP_USERNAME }}>
          body: |
            Hello,

            The automation test run for '${{ github.repository }}' has completed.
            Run Status: **${{ needs.test.result }}**

            Repository      : ${{ github.repository }}
            Workflow        : ${{ github.workflow }}
            Run ID          : ${{ github.run_id }}
            Run Number      : ${{ github.run_number }}
            Event Type      : ${{ github.event_name }}
            Triggered By    : ${{ github.actor }}
            Branch          : ${{ github.ref_name }}
            Commit          : https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            Commit Message  : ${{ needs.test.outputs.commit_message_text }}

            Test Summary:
            Total Tests     : ${{ needs.test.outputs.total }}
            Tests Passed    : ${{ needs.test.outputs.passed }}
            Tests Failed    : ${{ needs.test.outputs.failed }}
            Duration        : ${{ needs.test.outputs.duration }} seconds

            View the full Allure Report:
            ${{ steps.deployment.outputs.page_url }}

            Regards,
            GitHub Actions CI