name: CI – Run Tests and Email Notification

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements.txt

      - name: Make run_tests.sh executable
        run: chmod +x ./run_tests.sh

      - name: Run tests (no Allure)
        run: |
          ./run_tests.sh --no-report

      # (Optional) If you want to capture test metrics, you would add steps here
      # to parse logs or JSON output and set them as job outputs for use in the email.

  notify:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: |
            [CI] Test Results – ${{ github.repository }} | ${{ github.run_started_at }}
          to: saivamsikolla@gmail.com
          from: GitHub Actions CI <${{ secrets.SMTP_USERNAME }}>
          body: |
            ==== PROJECT: ${{ github.repository }} | RELEASE: ${{ github.ref_name }} ====

            **Execution Summary**  
            • Date & Time: ${{ github.run_started_at }}  
            • Triggered By: ${{ github.actor }}  
            • Branch/Tag: ${{ github.ref_name }}  
            • Commit: ${{ github.sha }}  
            • Build URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            **Key Metrics**  
            • Total Tests: {{TOTAL_TESTS}}  
            • Passed: {{PASSED_TESTS}}  
            • Failed: {{FAILED_TESTS}}  
            • Skipped: {{SKIPPED_TESTS}}  
            • Pass %: {{PASS_PERCENTAGE}}

            ==== FAILED TESTS ====  
            {{#each FAILED_LIST}}  
            • Test ID: {{this.id}}  
              Name: {{this.name}}  
              Module: {{this.module}}  
              Error: {{this.error_snippet}}  
              Log/Screenshot: [View]({{this.log_url}})  
            {{/each}}

            ==== SKIPPED TESTS ====  
            {{#each SKIPPED_LIST}}  
            • Test ID: {{this.id}}  
              Name: {{this.name}}  
              Module: {{this.module}}  
              Reason: {{this.skip_reason}}  
            {{/each}}

            ==== PASSED TESTS ====  
            {{#each PASSED_LIST}}  
            • Test ID: {{this.id}} – {{this.name}}  
            {{/each}}

            ==== ACTION ITEMS ====  
            • [View Full Test Report](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})  
            • [Open CI Build Details](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

            Regards,  
            GitHub Actions CI
