name: CI with Dynamic Allure Report and Email

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    outputs:
      total: ${{ steps.summary.outputs.total }}
      passed: ${{ steps.summary.outputs.passed }}
      failed: ${{ steps.summary.outputs.failed }}
      duration: ${{ steps.summary.outputs.duration }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Or your project's Python version

      - name: Install system dependencies (jq and bc for summary)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq bc

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements.txt

      - name: Make run_tests.sh executable
        run: chmod +x ./run_tests.sh

      - name: Run Tests (All browsers, parallel, no HTML report from script)
        run: ./run_tests.sh --all-browsers --parallel-browsers -p 2 --no-report
        # This command runs a comprehensive test suite.
        # --no-report tells run_tests.sh to skip its internal Allure HTML generation
        # and also skips its check for the allure CLI, as this CI job will handle generation.
        # Test results will be in allure-results/parallel-multi-browser/ by default with these flags.

      - name: Generate Allure Report HTML
        id: allure_report_generation
        run: |
          # Download and set up Allure CLI (Consider using setup-allure action for more robustness)
          # Using a more recent Allure version for better features and compatibility.
          ALLURE_VERSION="2.27.0" # You can update this to the latest stable Allure version
          wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.zip
          unzip allure-${ALLURE_VERSION}.zip
          # The run_tests.sh script with --all-browsers --parallel-browsers outputs to allure-results/parallel-multi-browser
          # Ensure this path matches the output directory of your run_tests.sh command in the previous step.
          ./allure-${ALLURE_VERSION}/bin/allure generate allure-results/parallel-multi-browser --clean -o allure-report
        # continue-on-error: true # Uncomment if you want the workflow to proceed even if report generation fails

      - name: Upload Allure Report Artifact for GitHub Pages
        if: success() || failure() # Upload report even if tests fail, as long as this step runs
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./allure-report"

      - name: Extract Test Summary
        if: success() || failure() # Attempt to extract summary even if tests fail but report was generated
        id: summary
        run: |
          STATS_FILE="allure-report/widgets/summary.json"
          if [ -f "$STATS_FILE" ]; then
            TOTAL=$(jq '.statistic.total' $STATS_FILE)
            PASSED=$(jq '.statistic.passed' $STATS_FILE)
            FAILED=$(jq '.statistic.failed' $STATS_FILE)
            # Handle cases where values might be null if no tests ran or summary.json is malformed
            TOTAL=${TOTAL:-0}
            PASSED=${PASSED:-0}
            FAILED=${FAILED:-0}
            
            DURATION_MS=$(jq '.time.duration' $STATS_FILE)
            DURATION_MS=${DURATION_MS:-0} # Default to 0 if null
            DURATION_SEC=$(echo "scale=2; $DURATION_MS / 1000" | bc)

            echo "total=$TOTAL" >> $GITHUB_OUTPUT
            echo "passed=$PASSED" >> $GITHUB_OUTPUT
            echo "failed=$FAILED" >> $GITHUB_OUTPUT
            echo "duration=$DURATION_SEC" >> $GITHUB_OUTPUT
            echo "Summary extracted: Total=$TOTAL, Passed=$PASSED, Failed=$FAILED, Duration=${DURATION_SEC}s"
          else
            echo "Warning: summary.json not found at $STATS_FILE. Setting default values for summary outputs."
            echo "total=0" >> $GITHUB_OUTPUT
            echo "passed=0" >> $GITHUB_OUTPUT
            echo "failed=0" >> $GITHUB_OUTPUT
            echo "duration=0.00" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: test
    runs-on: ubuntu-latest
    # Run deploy step always after 'test' job finishes, regardless of its outcome,
    # so the report (potentially showing failures) is deployed.
    if: always()
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Send Allure Report Email
        # Send email only if the test job itself succeeded or failed (not cancelled/skipped)
        # and if SMTP secrets are likely configured (simple check if not empty).
        if: (needs.test.result == 'success' || needs.test.result == 'failure') && ${{ secrets.SMTP_USERNAME != '' }} && ${{ secrets.SMTP_PASSWORD != '' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: >
            Allure Report - ${{ github.repository }} | Status: ${{ needs.test.result }} | Event: ${{ github.event_name }}
          to: saivamsikolla@gmail.com # Consider making this a repository secret or workflow input for flexibility
          from: GitHub Actions CI <${{ secrets.SMTP_USERNAME }}> # Use your SMTP username as the sender's email
          body: |
            Hello,

            The automation test run for '${{ github.repository }}' has completed.
            Run Status: **${{ needs.test.result }}**

            Repository      : ${{ github.repository }}
            Workflow        : ${{ github.workflow }}
            Run ID          : ${{ github.run_id }}
            Run Number      : ${{ github.run_number }}
            Event Type      : ${{ github.event_name }}
            Triggered By    : ${{ github.actor }}
            Branch          : ${{ github.ref_name }}
            Commit          : https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            Commit Message  : ${{needs.test.outputs.commit_message || github.event.head_commit.message || github.event.pull_request.title }}

            Test Summary:
            Total Tests     : ${{ needs.test.outputs.total }}
            Tests Passed    : ${{ needs.test.outputs.passed }}
            Tests Failed    : ${{ needs.test.outputs.failed }}
            Duration        : ${{ needs.test.outputs.duration }} seconds

            View the full Allure Report:
            ${{ steps.deployment.outputs.page_url }}

            Regards,
            GitHub Actions CI