name: CI with Allure Email Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements.txt

      - name: Run Tests
        run: ./run_tests.sh

      - name: Generate Allure Report
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.14.0/allure-2.14.0.zip
          unzip allure-2.14.0.zip
          ./allure-2.14.0/bin/allure generate allure-results --clean -o allure-report

      - name: Zip Allure Report
        run: zip -r allure-report.zip allure-report

      - name: Email Allure Report (.zip)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 🧪 Allure Report: ${{ github.repository }} — ${{ github.event_name }}
          to: saivamsikolla@gmail.com
          from: GitHub Actions <saivamsikolla@gmail.com>
          body: |
            👋 Hello Vamsi,

            ✅ Your automation test suite just ran on **${{ github.repository }}**

            📌 **Triggered by**: `${{ github.event_name | title }}`  
            🕒 **Commit Time**: `${{ github.event.head_commit.timestamp || github.event.pull_request.updated_at }}`  
            🔧 **Commit Message**: "${{ github.event.head_commit.message || github.event.pull_request.title }}"

            📎 The attached ZIP contains the full Allure test report.

            📬 Triggered by: `${{ github.actor }}`
            🧠 Branch: `${{ github.ref_name }}`

            🚀 Keep testing with confidence!

            – GitHub Actions Bot 🤖

          attachments: allure-report.zip
