name: CI – Run Tests and Publish Allure Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements.txt

      - name: Run pytest and produce Allure results
        run: |
          pytest --alluredir=allure-results

      - name: Download and unzip Allure CLI
        run: |
          ALLURE_VERSION="2.27.0"
          wget -qO allure.zip \
            https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.zip
          unzip -q allure.zip
          rm allure.zip

      - name: Generate Allure HTML report
        run: |
          ALLURE_VERSION="2.27.0"
          ./allure-${ALLURE_VERSION}/bin/allure generate allure-results --clean -o allure-report

      - name: Upload Allure report as Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4

      - name: Zip up Allure report for email
        run: |
          zip -r allure-report.zip allure-report

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: |
            [CI] ${{ github.repository }} – Allure Report Published
          to: saivamsikolla@gmail.com
          from: GitHub Actions CI <${{ secrets.SMTP_USERNAME }}>
          body: |
            Hello,

            Your Allure report is live:

            • View online: ${{ steps.deploy-pages.outputs.page_url }}

            You can also download the attached ZIP to view the report locally.

            Regards,
            GitHub Actions CI
          attachments: allure-report.zip
