# This GitHub Actions workflow executes Selenium UI tests using a Selenium Grid.
# It includes the following major blocks:
# 1. Grid Services: Sets up Selenium Hub and browser nodes (Chrome, Firefox) as services.
# 2. Test Execution: Checks out code, sets up Python, installs dependencies,
#    waits for the Grid, and then runs pytest against multiple browsers.
#    Allure results are generated separately for each browser.
# 3. Allure Report Generation: Downloads the Allure CLI and generates a combined
#    HTML report from the results of all browser tests.
# 4. GitHub Pages Deployment: Uploads the generated Allure report as a GitHub Pages
#    artifact and deploys it, making the report accessible online.
# 5. Email Notification: Sends an email notification with a link to the deployed
#    Allure report upon completion.

name: Selenium Grid CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering of the workflow

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  ci:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    services:
      # Selenium Grid Services: Hub and browser nodes
      selenium-hub:
        image: selenium/hub:4.18.1
        ports:
          - 4444:4444
          - 4442:4442
          - 4443:4443
        options: >-
          --health-cmd "curl -f http://localhost:4444/wd/hub/status || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      node-chrome:
        image: selenium/node-chrome:4.18.1-20240224
        options: >-
          --shm-size="2g"
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
          SE_NODE_MAX_SESSIONS: 4
          SE_NODE_OVERRIDE_MAX_SESSIONS: true
          SE_NODE_SESSION_TIMEOUT: 300
          SE_START_XVFB: false
      
      node-firefox:
        image: selenium/node-firefox:4.18.1-20240224
        options: >-
          --shm-size="2g"
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
          SE_NODE_MAX_SESSIONS: 4
          SE_NODE_OVERRIDE_MAX_SESSIONS: true
          SE_NODE_SESSION_TIMEOUT: 300
          SE_START_XVFB: false

    steps:
      # Initial setup steps
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build test framework image
        run: |
          docker build -t test-framework:latest .
          docker images

      - name: Debug environment
        run: |
          echo "Python version:"
          python --version
          echo "Pip version:"
          pip --version
          echo "Docker version:"
          docker --version
          echo "Docker images:"
          docker images
          echo "Docker containers:"
          docker ps -a
          echo "Network status:"
          netstat -tulpn || true

      - name: Debug Selenium Grid
        run: |
          echo "Checking Selenium Grid status..."
          curl -v http://localhost:4444/status || true
          echo "Checking Grid Console..."
          curl -v http://localhost:4444/ui/index.html || true
          echo "Checking node registration..."
          curl -v http://localhost:4444/grid/console || true

      - name: Wait for Selenium Grid
        timeout-minutes: 2
        run: |
          echo "Waiting for Selenium Grid to be ready..."
          end=$((SECONDS + 120))
          while [ $SECONDS -lt $end ]; do
            if curl -s --fail http://localhost:4444/status | jq -e '.value.ready == true' > /dev/null; then
              echo "✅ Selenium Grid is ready!"
              curl -s http://localhost:4444/status | jq .
              break
            fi
            echo "⏳ Grid not ready, retrying in 5s..."
            sleep 5
          done
          if ! curl -s --fail http://localhost:4444/status | jq -e '.value.ready == true' > /dev/null; then
            echo "❌ Timeout waiting for Selenium Grid"
            exit 1
          fi

      - name: Create Allure results directories
        run: |
          mkdir -p allure-results/{chrome,firefox}
          chmod -R 777 allure-results

      # Test Execution Steps using Docker container
      - name: Run tests on Chrome
        id: chrome_tests
        continue-on-error: true
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
          BROWSER: chrome
        run: |
          echo "Running Chrome tests..."
          docker run --rm \
            --network="host" \
            --shm-size=2g \
            -v "${PWD}:/usr/src/app" \
            -w /usr/src/app \
            -e BROWSER \
            -e SELENIUM_REMOTE_URL \
            -e PYTHONUNBUFFERED=1 \
            test-framework:latest \
            pytest Tests/ \
              --browser="${BROWSER}" \
              --remote-url="${SELENIUM_REMOTE_URL}" \
              -n 2 \
              --alluredir=allure-results/chrome \
              --reruns 2 \
              --reruns-delay 1 \
              -v

      - name: Run tests on Firefox
        id: firefox_tests
        continue-on-error: true
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
          BROWSER: firefox
        run: |
          echo "Running Firefox tests..."
          docker run --rm \
            --network="host" \
            --shm-size=2g \
            -v "${PWD}:/usr/src/app" \
            -w /usr/src/app \
            -e BROWSER \
            -e SELENIUM_REMOTE_URL \
            -e PYTHONUNBUFFERED=1 \
            test-framework:latest \
            pytest Tests/ \
              --browser="${BROWSER}" \
              --remote-url="${SELENIUM_REMOTE_URL}" \
              -n 2 \
              --alluredir=allure-results/firefox \
              --reruns 2 \
              --reruns-delay 1 \
              -v

      - name: Check test results
        run: |
          if [[ "${{ steps.chrome_tests.outcome }}" == "failure" && "${{ steps.firefox_tests.outcome }}" == "failure" ]]; then
            echo "❌ Both Chrome and Firefox tests failed"
            exit 1
          fi

      # Allure Report Generation
      - name: Generate Combined Allure Report
        if: always()
        run: |
          echo "Generating Allure report..."
          ls -la allure-results/chrome || true
          ls -la allure-results/firefox || true
          
          # Create base report structure even if no results
          mkdir -p allure-report
          
          if [ -d "allure-results/chrome" ] || [ -d "allure-results/firefox" ]; then
            docker run --rm \
              -v "${PWD}:/usr/src/app" \
              -w /usr/src/app \
              test-framework:latest \
              allure generate \
                allure-results/chrome \
                allure-results/firefox \
                --clean \
                -o allure-report
          else
            echo "<html><body><h1>No test results available</h1></body></html>" > allure-report/index.html
          fi
          
          echo "Report generation complete"
          ls -la allure-report

      # GitHub Pages Deployment
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: allure-report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: always()

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: '[CI] Selenium Grid Test Results - ${{ github.repository }}'
          to: saivamsikolla@gmail.com
          from: GitHub Actions CI Bot <${{ secrets.SMTP_FROM_EMAIL_ADDRESS }}>
          html_body: |
            <h2>Selenium Grid Test Results</h2>
            <p><strong>Repository:</strong> ${{ github.repository }}</p>
            <p><strong>Workflow Run:</strong> <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Run Details</a></p>
            <p><strong>Commit:</strong> ${{ github.sha }}</p>
            <p><strong>Branch:</strong> ${{ github.ref_name }}</p>
            <p><strong>Triggered by:</strong> ${{ github.actor }}</p>
            <p><strong>Chrome Tests:</strong> ${{ steps.chrome_tests.outcome }}</p>
            <p><strong>Firefox Tests:</strong> ${{ steps.firefox_tests.outcome }}</p>
            <br>
            <p><strong>Test Report:</strong> <a href="${{ steps.deployment.outputs.page_url }}">View Allure Report</a></p>
            <br>
            <p>This is an automated message from GitHub Actions CI.</p>
