name: CI – Run Tests, Deploy Allure, and Email

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements.txt

      - name: Run pytest and collect Allure results
        run: |
          pytest --alluredir=allure-results

      - name: Download and unzip Allure CLI
        run: |
          ALLURE_VERSION="2.27.0"
          wget -qO allure.zip \
            https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.zip
          unzip -q allure.zip
          rm allure.zip

      - name: Generate Allure HTML report
        run: |
          ALLURE_VERSION="2.27.0"
          ./allure-${ALLURE_VERSION}/bin/allure generate allure-results --clean -o allure-report

      - name: Publish Allure report to GitHub Pages
        id: deploy_pages
        uses: actions/deploy-pages@v4
        with:
          # By default, this picks up the ./allure-report folder
          folder: allure-report

      - name: Zip up Allure report for email
        run: |
          zip -r allure-report.zip allure-report

      - name: Send email notification (with Allure ZIP attached)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: |
            [CI] ${{ github.repository }} – Allure Report (run on ${{ github.run_started_at }})
          to: saivamsikolla@gmail.com
          from: GitHub Actions CI <${{ secrets.SMTP_USERNAME }}>
          body: |
            Hello,

            The tests have completed, and the Allure report is now live.

            • **View interactive report online:**  
              ${{ steps.deploy_pages.outputs.page_url }}

            • **Download attached ZIP** to browse locally (unzips to the exact same HTML files you see on Pages).

            Regards,  
            GitHub Actions CI
          attachments: allure-report.zip
