      - name: Send email with badge in subject
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: |
            [![CI Badge](https://github.com/saivamsikolla-qa/selenium-pom-ui-tests-python/actions/workflows/CI.yml/badge.svg)]
            Test Results – ${{ github.repository }} | ${{ needs.test.outputs.passed }}/${{ needs.test.outputs.total }} passed
          to: saivamsikolla@gmail.com
          from: GitHub Actions CI <${{ secrets.SMTP_USERNAME }}>
          body: |
            **Test Execution Summary**  
            • Total run:   ${{ needs.test.outputs.total }}  
            • Passed:      ${{ needs.test.outputs.passed }}  
            • Failed:      ${{ needs.test.outputs.failed }}  

            **Detailed report:**  
            • CI build page: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Regards,  
            GitHub Actions CI
