name: CI – Run Tests and Email Notification

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements.txt

      - name: Make run_tests.sh executable
        run: chmod +x ./run_tests.sh

      - name: Run tests (no Allure)
        run: |
          ./run_tests.sh --no-report

  notify:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: |
            Test Results – ${{ github.repository }} | ${{ github.sha }}
          to: saivamsikolla@gmail.com
          from: GitHub Actions CI <${{ secrets.SMTP_USERNAME }}>
          body: |
            Hello,

            The test run for '${{ github.repository }}' has completed.
            Run Status     : ${{ needs.test.result }}
            Branch         : ${{ github.ref_name }}
            Commit         : https://github.com/${{ github.repository }}/commit/${{ github.sha }}

            Regards,
            GitHub Actions CI
